[package]
name = "asche"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
description = "Provides an abstraction layer above ash to easier use Vulkan in Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hasenbanck/asche"
categories = ["graphics"]
keywords = ["vulkan", "erupt"]
edition = "2018"

[features]
default = ["tracing"]

[dependencies]
erupt = "0.17"
raw-window-handle = "0.3"
arrayvec = "0.5"
tracing = { version = "0.1", default-features = false, optional = true }
parking_lot = "0.11"
vk-alloc = { version = "0.4", features = ["tracing", "vk-buffer-device-address"] }

[dev-dependencies]
bytemuck = "1.5"
ddsfile = "0.4"
glam = { version = "0.12", features = ["bytemuck"] }
tracing-subscriber = { version = "0.2", default-features = false, features = ["fmt", "ansi", "env-filter"] }
# TODO "bundled" doesn't work on windows currently
sdl2 = { version = "0.34", default-features = false, features = ["raw-window-handle"] }

[build-dependencies]
shaderc = "0.7"
