[package]
name = "asche"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
description = "Provides an abstraction layer above ash to easier use Vulkan in Rust with minimal dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hasenbanck/asche"
categories = ["graphics"]
keywords = ["vulkan", "ash"]
edition = "2018"

[features]
default = ["tracing"]

[dependencies]
ash = "0.31"
raw-window-handle = "0.3.3"
tracing = { version = "0.1", default-features = false, features = ["std"], optional = true }
vk-alloc = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.2", default-features = false, features = ["fmt", "ansi"] }
winit = "0.24"
vk-shader-macros = "0.2"