[package]
name = "asche"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
description = "Provides an abstraction layer above ash to easier use Vulkan in Rust with minimal dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hasenbanck/asche"
categories = ["graphics"]
keywords = ["vulkan", "ash"]
edition = "2018"

[features]
default = ["tracing"]

[dependencies]
ash = "0.31"
parking_lot = { version = "0.11", optional = true }
tracing = { version = "0.1", default-features = false, features = ["std", "max_level_trace", "release_max_level_info"], optional = true }

[dev-dependencies]
anyhow = "1.0"
tracing-subscriber = { version = "0.2", default-features = false, features = ["ansi", "smallvec", "parking_lot"] }
winit = "0.24"

[profile.bench]
codegen-units = 1
lto = "thin"

[profile.release]
codegen-units = 1
lto = "thin"
